--- #YAML:1.0
name: WebSphere-MQTT-Client
version: 0.01
author:
  - Nicholas Humfrey, njh@ecs.soton.ac.uk
abstract: WebSphere MQ Telemetry Transport Client
license: restrictive
requires:
  Data::Dumper: 0
  Getopt::Std: 0
  Pod::Usage: 0
  Test: 1.00
  Time::HiRes: 0
build_requires:
  Module::Build: 0.20
provides:
  WebSphere::MQTT::Client:
    file: lib/WebSphere/MQTT/Client.pm
    version: 0.01
generated_by: Module::Build version 0.26
